### PR TITLE
Updated iPhone/iPad mobile devices

### PR DESCRIPTION
**Pull request by lbartoli79**

### CODE REVIEW

**Comment by pmeenan** [comment]
Did you mean to change the trhottle factor for the existing Android devices? Those are the baselines that you should be setting other throttles from because they were calibrated on real devices.

**Comment by lbartoli79** [comment]
Those two files www/settings/mobile_devices.ini docker/local/server/config/mobile_devices.ini are different, which one is correct?

**Comment by pmeenan** [comment]
I'm not sure why the docker container has a separate copy but the `www/settings/mobile_devices.ini` one is the authoritative file (and the one used by production).

Change LGTM

**Review by pmeenan — APPROVED** [review]

**Comment by lbartoli79** [comment]
@pmeenan Thanks for the clarification. I'm going to open another PR to align docker configuration with the one used in prod

**Review by claud-io — APPROVED** [review]

**Pull request merged**
