### PR TITLE
Fix FFMPEG Configure in docker

### PR DESCRIPTION
**Pull request by a-venger**
Fix for  #2902 #2957
Updated alpine image to 3.18 and added missing libraries

### CODE REVIEW

**Comment by Dgeorgiev90** [comment]
This worked for us... and it came right on time! Thanks @a-venger !

**Comment by dreadedhamish** [comment]
Awesome.

**Comment by a-venger** [comment]
@dreadedhamish indeed. There was a recent library update which started to fail the build.
I have updated the Dockerfile to eliminate such issues to happen in future.
Please try now and let me know if it works for you now.

**Comment by srvadmin** [comment]
This worked for me! Thanks @a-venger !

**Comment by radum** [comment]
This worked for me also. This PR should go in.

**Review by lbartoli79 — APPROVED** [review]

**Pull request merged**
